class_name BossMap
extends RefCounted
## THE WARDEN'S SANCTUM (72x38): an obsidian boss chamber in the Warden's
## own crimson-circuit art (blocks 5011-5015, generated by
## tools/gen_boss_sprites.ps1). Wide floor for slam-dodging, stepped side
## galleries and high perches for gun angles, broken pillars for beam
## cover, floating rune platforms, energy buttress curves to skate, and a
## central rune altar where the DOOM RAY materializes — all under a giant
## background summoning circle. Built in-memory only.

const W: int = 72
const H: int = 38

const WALL: int = 5011     # Obsidian plate, crimson circuit veins
const FLOOR_B: int = 5012  # Ribbed dark iron, glowing crimson seam
const RUNE: int = 5013     # Glowing crimson rune core
const VOID: int = 5014     # Black-violet depth fill
const ENERGY_B: int = 5015 # Crimson/violet energy (buttress curves)

# The Warden's flight envelope
const BOUNDS_MIN_X: float = 64.0
const BOUNDS_MAX_X: float = 1088.0
const BOUNDS_MIN_Y: float = 96.0
const FLOOR_Y: float = 544.0
const SUPER_POS: Vector2 = Vector2(576.0, 462.0)  # Above the rune altar


static func build() -> void:
	WorldManager.init_empty_world(W, H)
	WorldManager.free_blocks.clear()
	WorldManager.polylines.clear()
	WorldManager.wedge_pairs.clear()
	WorldManager.curve_colliders.clear()
	WorldManager.lines.clear()
	WorldManager.block_groups.clear()
	WorldManager.gravity_zones.zones.clear()
	WorldManager.spawn_points.clear()

	# ── Shell (2 thick, obsidian) ──
	for x in range(W):
		_fg(x, 0, WALL)
		_fg(x, 1, WALL)
		_fg(x, H - 1, WALL)
	for y in range(H):
		_fg(0, y, WALL)
		_fg(1, y, WALL)
		_fg(W - 2, y, WALL)
		_fg(W - 1, y, WALL)

	# ── Floor ──
	for x in range(2, W - 2):
		_fg(x, 34, FLOOR_B)
		_fg(x, 35, VOID)
		_fg(x, 36, VOID)

	# ── Side galleries (y28, top 448) + steps (y31, top 496) ──
	for x in range(4, 13):
		_fg(x, 28, FLOOR_B)
	for x in range(59, 68):
		_fg(x, 28, FLOOR_B)
	_fg(12, 28, RUNE)
	_fg(59, 28, RUNE)
	for x in range(13, 15):
		_fg(x, 31, WALL)
	for x in range(57, 59):
		_fg(x, 31, WALL)

	# ── High perches (y24, top 384) ──
	for x in range(5, 10):
		_fg(x, 24, FLOOR_B)
	for x in range(62, 67):
		_fg(x, 24, FLOOR_B)
	_fg(9, 24, RUNE)
	_fg(62, 24, RUNE)

	# ── Broken pillars (beam cover): floor -> y30, rune caps ──
	for y in range(30, 34):
		_fg(22, y, WALL)
		_fg(23, y, WALL)
		_fg(48, y, WALL)
		_fg(49, y, WALL)
	_fg(22, 30, RUNE)
	_fg(49, 30, RUNE)

	# ── Floating rune platforms (y20, top 320) ──
	for x in range(26, 29):
		_fg(x, 20, RUNE)
	for x in range(43, 46):
		_fg(x, 20, RUNE)

	# ── Central rune altar (wide base, top 480) — the DOOM RAY's cradle ──
	for x in range(33, 39):
		_fg(x, 32, WALL)
		_fg(x, 33, WALL)
	for x in range(34, 38):
		_fg(x, 30, FLOOR_B)
		_fg(x, 31, WALL)
	_fg(34, 30, RUNE)
	_fg(37, 30, RUNE)

	# ── Ceiling ribs (hanging obsidian, rune tips) ──
	for rx in [12, 24, 47, 59]:
		_fg(rx, 2, WALL)
		_fg(rx, 3, WALL)
		_fg(rx, 4, RUNE)

	# ── Background: the giant summoning circle behind the Warden's hover ──
	for y in range(5, 22):
		for x in range(28, 45):
			var dx: float = float(x) - 36.0
			var dy: float = float(y) - 13.0
			var d: float = sqrt(dx * dx + dy * dy)
			if d >= 5.6 and d <= 7.0:
				WorldManager.set_bg_tile(x, y, RUNE + 100)
	WorldManager.set_bg_tile(36, 13, RUNE + 100)
	WorldManager.set_bg_tile(35, 13, WALL + 100)
	WorldManager.set_bg_tile(37, 13, WALL + 100)
	WorldManager.set_bg_tile(36, 12, WALL + 100)
	WorldManager.set_bg_tile(36, 14, WALL + 100)
	# Altar column + gallery back panels
	for y in range(20, 30):
		WorldManager.set_bg_tile(35, y, WALL + 100)
		WorldManager.set_bg_tile(36, y, WALL + 100)
	for y in range(25, 28):
		for x in range(5, 12):
			WorldManager.set_bg_tile(x, y, VOID + 100)
		for x in range(60, 67):
			WorldManager.set_bg_tile(x, y, VOID + 100)

	# ── Energy buttress curves (both ends buried) ──
	WorldManager.add_polyline(_spline([
		Vector2(18, 400), Vector2(30, 470), Vector2(90, 526), Vector2(160, 546), Vector2(220, 578),
	]), "both", ENERGY_B)
	WorldManager.add_polyline(_spline([
		Vector2(1134, 400), Vector2(1122, 470), Vector2(1062, 526), Vector2(992, 546), Vector2(932, 578),
	]), "both", ENERGY_B)

	WorldManager.spawn_points.append(Vector2(8, 32))

	WorldManager.tile_changed.emit(0, 0, 0)
	WorldManager.free_blocks_changed.emit()
	WorldManager.polylines_changed.emit()
	WorldManager.gravity_zones.zones_changed.emit()


static func add_weapon_pads(ws: WeaponSystem) -> void:
	ws.add_pad(Vector2(320, 526), "blaster")     # Left floor
	ws.add_pad(Vector2(832, 526), "blaster")     # Right floor
	ws.add_pad(Vector2(128, 434), "scatter")     # Left gallery
	ws.add_pad(Vector2(1024, 434), "scatter")    # Right gallery
	ws.super_pos = SUPER_POS


static func _fg(x: int, y: int, id: int) -> void:
	if x >= 0 and x < WorldManager.world_width and y >= 0 and y < WorldManager.world_height:
		WorldManager.fg_tiles[y][x] = id


static func _spline(points: Array) -> PackedVector2Array:
	var out: PackedVector2Array = PackedVector2Array()
	var cp: Array = [points[0] - (points[1] - points[0])]
	cp.append_array(points)
	cp.append(points[-1] + (points[-1] - points[-2]))
	for seg in range(1, cp.size() - 2):
		var p0: Vector2 = cp[seg - 1]
		var p1: Vector2 = cp[seg]
		var p2: Vector2 = cp[seg + 1]
		var p3: Vector2 = cp[seg + 2]
		var steps: int = maxi(4, int(ceil(p1.distance_to(p2))))
		for i in range(steps):
			var t: float = float(i) / float(steps)
			var tt: float = t * t
			var ttt: float = tt * t
			var pos: Vector2 = 0.5 * ((2.0 * p1) + (-p0 + p2) * t + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * tt + (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * ttt)
			if out.size() == 0 or out[-1].distance_to(pos) > 1.0:
				out.append(pos)
	if out.size() > 0 and out[-1].distance_to(points[-1]) > 0.5:
		out.append(points[-1])
	return out
